# Generated by Django 3.2.8 on 2021-11-04 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatty_channels_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatroom',
            old_name='Created',
            new_name='created',
        ),
    ]
